[package]
name = "project-toot-sdk"
version = "0.0.1"
edition = "2021"

[dependencies]
borsh = { version = "~1.3", features = [ "derive" ] }
ed25519-dalek = { version = "~2.1", features = [ "digest" ] }
